### ISSUE TITLE
【功能建议】认出是谁在说话

### ISSUE THREAD

**Issue by ChenXu233** [LiteyukiStudio/nonebot-plugin-marshoai#1]
如下：
```
用户A：marsho 我是谁
marsho： 你是用户A，我的好朋友喵。
用户B：marsho 我是谁
marsho： 你是用户B，和我的开发者关系很好喵。
```

然后能否通过不同的人，回复不同的语气呢？
比如：
```
用户A：marsho 看看你的
marsho：有什么好看的喵！笨蛋喵！
用户B：marsho 看看你的
marsho：要这...这样吗，那.....本喵就勉为其难给你看看喵。
```

**Comment by Asankilp** [comment]
这个功能我也想过（基于提取用户昵称实现），但群u认为一些人的昵称过于奇怪可能会误导AI（

**Comment by Asankilp** [comment]
我的新想法是提供一个nickname命令让用户自己设置自己的昵称，然而现在没时间写代码了）

**Comment by snowykami** [comment]
抓

**Comment by ChlorideP** [comment]
> nickname命令让用户自己设置自己的昵称

紫色专属牌子或许可以是个 fallback 参考。不然总归是低效了些。
当然我是 fw，我只会口嗨（

**Comment by ChenXu233** [comment]
> 我的新想法是提供一个nickname命令让用户自己设置自己的昵称，然而现在没时间写代码了）

或许我也可以帮忙？

**Comment by ChenXu233** [comment]
> 抓

喵~

**Comment by Asankilp** [comment]
> > 我的新想法是提供一个nickname命令让用户自己设置自己的昵称，然而现在没时间写代码了）
> 
> 或许我也可以帮忙？

喵

**Comment by Asankilp** [comment]
v0.3已初步实现（（（

**Comment by Asankilp** [comment]
“特定语气回答”我觉得可以靠用户自己的消息进行调整，所以没做（）
