### ISSUE TITLE
[bug]一些问题

### ISSUE THREAD

**Issue by mintianzan** [LiteyukiStudio/nonebot-plugin-marshoai#17]
1.当内容被限制的时候有时会输出报错内容
 1.1能否在配置项里控制内容限制？

2.上下文记录太多，很容易超token，可以考虑自动遗忘一些或者分用户存储？目前好像是分群存储的

3.用户识别有一些小问题，比如在人设里写了：“aaa”是你的朋友，当nickname为“aaa”时并不会认为是人设里提到的“aaa”

1的消息，直接发送了：
(content_filter) The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766
Code: content_filter
Message: The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766
Inner error: {
    "code": "ResponsibleAIPolicyViolation",
    "content_filter_result": {
        "hate": {
            "filtered": false,
            "severity": "safe"
        },
        "jailbreak": {
            "filtered": false,
            "detected": false
        },
        "self_harm": {
            "filtered": false,
            "severity": "safe"
        },
        "sexual": {
            "filtered": true,
            "severity": "medium"
        },
        "violence": {
            "filtered": false,
            "severity": "safe"
        }
    }
}
消息已被内容过滤器过滤。请调整聊天内容后重试。

**Comment by Asankilp** [comment]
1. 默认情况下使用的API内容过滤器强制开启，无法控制限制的内容（如果可以使用其它提供商的API的话，可以配置`MARSHOAI_AZURE_ENDPOINT`来使用别家的模型（（

2. 自动遗忘在不提示用户的情况下可能让用户感到困惑（？）所以我觉得用户手动重置比较好一些（？？）（但我觉得有必要加一点省token措施），上下文的存储是每个群聊及每个私聊各自独立
3. 可能是提示词的问题？如果使用夸赞名单功能设定认识的人的话，一般是可以让AI认识的（（（ 
![Screenshot_2024-12-05-01-24-07-592_com tencent mobileqq-edit](https://github.com/user-attachments/assets/2433d78b-965c-4b78-865e-5095d9ed578b)

**Comment by mintianzan** [comment]
1.问题主要出在会把整段报错发送出去，而不是仅提示内容不合规范
2.一般会设定一个最大上下文数量
3.我再看看夸赞名单的部分，这个应该没问题了
4.新问题，在正常运行大概半天后，现在会在response = await make_chat(...)这一步意外结束，并不会触发except
![image](https://github.com/user-attachments/assets/363a9adc-a605-4581-b1ca-8fd166030ada)
这一步没有报错也没有任何回复，响应事件也没有后续处理了
5.可能是特例，但在运行插件之后ctrl+C退出nonebot的时候会卡在shutdown
![image](https://github.com/user-attachments/assets/688ca178-b379-4454-a7e6-02fd383c750c)

**Comment by mintianzan** [comment]
补充一下1的截图
![image](https://github.com/user-attachments/assets/e8b9efac-89de-4d29-b521-43539499b1ee)
是会直接全部发送出来

**Comment by Asankilp** [comment]
> 1.问题主要出在会把整段报错发送出去，而不是仅提示内容不合规范 2.一般会设定一个最大上下文数量 3.我再看看夸赞名单的部分，这个应该没问题了 4.新问题，在正常运行大概半天后，现在会在response = await make_chat(...)这一步意外结束，并不会触发except ![image](https://private-user-images.githubusercontent.com/140377173/392633329-363a9adc-a605-4581-b1ca-8fd166030ada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzI1NDQsIm5iZiI6MTczMzM3MjI0NCwicGF0aCI6Ii8xNDAzNzcxNzMvMzkyNjMzMzI5LTM2M2E5YWRjLWE2MDUtNDU4MS1iMWNhLThmZDE2NjAzMGFkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwNDE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmZiMDI5YmY2MGNiZjBlZDZmNGQzNTE0OWQyYzlmOWI5YzhiMGY4MGJhNGE2OWIwNTVjYjhiMDMzY2JiOGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D9yZ4V6ZXy1LbLY5mxmiY-IL8WBy_nLnO8hT-q_2mPQ) 这一步没有报错也没有任何回复，响应事件也没有后续处理了 5.可能是特例，但在运行插件之后ctrl+C退出nonebot的时候会卡在shutdown ![image](https://private-user-images.githubusercontent.com/140377173/392633704-688ca178-b379-4454-a7e6-02fd383c750c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzI1NDQsIm5iZiI6MTczMzM3MjI0NCwicGF0aCI6Ii8xNDAzNzcxNzMvMzkyNjMzNzA0LTY4OGNhMTc4LWIzNzktNDQ1NC1hN2U2LTAyZmQzODNjNzUwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwNDE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTJlNTRiMjlkYmEyOWI2ZmM5M2VkOTkxMzhhYzc1YjhkMzNmMzQ2NGE5NTZkNmRlMjIyMmQ2YTMwYjA2MTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b6YFA0JB8ef7NeR90Sm6HcZyXh-N_F0sRfV7Moa99p0)

1. 主要是Azure AI Inference SDK 的错误处理太拉了（遇到API返回的错误只会抛出一个`HttpResponseError`异常，似乎不能设定为返回错误原始信息，导致错误处理很麻烦），并且只有GPT模型会在报错中带上违规内容的详细，其它模型是不会带的([SDK里的定义](https://github.com/Azure/azure-sdk-for-python/blob/b03ef525432249dc56d036c8ff4901ef21fc60a6/sdk/ai/azure-ai-inference/azure/ai/inference/aio/_patch.py#L403))，可能之后会优化（咕咕咕）
2. 最大上下文限制的功能目前没有添加的计划（但是早期代码有非常粗暴的实现）
4. 卡在`make_chat`似乎是因为模型配额用完了，以前会抛出异常的，不知道为什么现在会卡住，原因还没找到（）遇到的话只能kill掉bot进程然后换成其他模型或者换个能用的token了 TwT
