### ISSUE TITLE
这是为啥，我已经设置了token了呀

### ISSUE THREAD

**Issue by MuliyStudio** [LiteyukiStudio/nonebot-plugin-marshoai#2]
![99ffefeb46682c43335ac1dd1a087399](https://github.com/user-attachments/assets/99774bc1-1703-42db-b874-4a222bfcc41b)

**Comment by Asankilp** [comment]
申请了GitHub models但是还处于waitlist阶段，要等几天直到通过才能用

**Comment by Asankilp** [comment]
![Screenshot_2024-09-06-12-57-15-617_com microsoft office outlook](https://github.com/user-attachments/assets/a446991f-bd62-401c-b78a-0bee615c7d16)
通过了之后会发一份像这样的邮件

**Comment by Asankilp** [comment]
~~也可以试试问问身边的hxd有没有能用的token（（（~~

**Comment by MuliyStudio** [comment]
好的非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月16日(周三) 凌晨1:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LiteyukiStudio/nonebot-plugin-marshoai] 这是为啥，我已经设置了token了呀 (Issue #2)




 
也可以试试问问身边的hxd有没有能用的token（（（
