### ISSUE TITLE
请问如果需要手动添加依赖的话，需要哪些包

### ISSUE THREAD

**Issue by bailanguanjun** [LiteyukiStudio/nonebot-plugin-marshoai#20]
请问如果需要手动添加依赖的话，需要哪些包，大佬能否给出一个requirements

**Comment by Asankilp** [comment]
依赖的包都写在`pyproject.toml`里，使用`pdm install`可以创建一个虚拟环境然后安装这些依赖

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: bailanguanjun ***@***.***>
Sent: Thursday, December 5, 2024 8:49:01 PM
To: LiteyukiStudio/nonebot-plugin-marshoai ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LiteyukiStudio/nonebot-plugin-marshoai] 请问如果需要手动添加依赖的话，需要哪些包 (Issue #20)


请问如果需要手动添加依赖的话，需要哪些包，大佬能否给出一个requirements

―

**Comment by EillesWan** [comment]
如果手动安装也是这样，你可以直接去 [pyproject.toml](../pyproject.toml) 里的 `dependencies` 下面逐一 pip install 之
